 @ECHO off

SET userId=%~1
SET taskId=%~2
SET render=%~3
SET txt=%~4
SET startframe=%~5
SET endframe=%~6
SET byframe=%~7
SET proj=%~8
SET mb=%~9


shift 
SET RD=%~9
SET _RD=D:/work/render/%taskId%/output/%startframe%_%endframe%_%byframe%

ECHO task info:
	ECHO	userId:		%userId%
	ECHO	taskId:		%taskId%
	ECHO	render:		%render%
	ECHO	txt:	%txt%
	ECHO	startframe:	%startframe%
	ECHO	endframe:	%endframe%
	ECHO	byframe:	%byframe%
	ECHO	proj:	%proj%
	ECHO	mb:	%mb%
	ECHO	_bat_opt:	%_bat_opt%


if "%userId%"=="1819310" goto render_1819310
if "%userId%"=="1821185" goto render_1821185
goto end


:render_1821185
    ECHO.
    ECHO OF3D-CPU-THS RENDER SCRIPT RUNNING @ %userId%
    SET _V_MAYA=2015
    SET _MAYAROOT=C:\Program Files\Autodesk\Maya%_V_MAYA%
    SET _USER_CONFIG_ROOT=B:\custom_config\1821185
    SET _USER_SCRIPT_MEL=%_USER_CONFIG_ROOT%\scripts\mel
    SET _USER_PLUG_INS=%_USER_CONFIG_ROOT%\plugins
    SET _USER_PLUG_IN_OPIUMPIPE=%_USER_PLUG_INS%\opiumPipe
    SET _USER_PLUG_IN_OPIUMPIPE_BIN=%_USER_PLUG_IN_OPIUMPIPE%\bin
    SET _USER_PLUG_IN_OPIUMPIPE_MLL=%_USER_PLUG_IN_OPIUMPIPE%\mll
    SET _USER_PLUG_IN_MTOA=%_USER_PLUG_INS%\mtoa_1.2.2.0
    
    SET _USER_SHADERS=%_USER_CONFIG_ROOT%\shaders
    SET _USER_SHADERS_ALSHADERS=%_USER_SHADERS%\alShaders-win-1.0.0rc11-ai4.2.2.0
    SET _USER_SHADERS_ALSHADERS_BIN=%_USER_SHADERS_ALSHADERS%\bin
    SET _USER_SHADERS_ALSHADERS_AE=%_USER_SHADERS_ALSHADERS%\ae
    SET _USER_SHADERS_OF_ALSHADERS=%_USER_SHADERS%\alShaders-OF-2015
    SET _USER_SHADERS_OF_ALSHADERS_BIN=%_USER_SHADERS_OF_ALSHADERS%
    SET _USER_SHADERS_OF_ALSHADERS_AE=%_USER_SHADERS_OF_ALSHADERS%\ae
    
    SET _USER_MAYA_MODULE_PATH=%_USER_PLUG_IN_MTOA%
    
    SET MAYA_PLUG_IN_PATH=%_USER_PLUG_IN_OPIUMPIPE_MLL%;%_USER_PLUG_IN_MTOA%\plug-ins
    SET MAYA_SCRIPT_PATH=%_USER_SCRIPT_MEL%
    SET MTOA_TEMPLATES_PATH=%_USER_SHADERS_ALSHADERS_AE%;%_USER_SHADERS_OF_ALSHADERS_AE%
    SET MAYA_MODULE_PATH=%_USER_MAYA_MODULE_PATH%;%_USER_MAYA_PLUG_IN_PATH%
    SET MAYA_RENDER_DESC_PATH=%_USER_PLUG_IN_MTOA%
    SET ARNOLD_PLUGIN_PATH=%_USER_SHADERS_ALSHADERS_BIN%;%_USER_SHADERS_OF_ALSHADERS_BIN%
    SET PATH=%PATH%;%_USER_PLUG_IN_OPIUMPIPE_BIN%;%_USER_PLUG_IN_MTOA%\bin
    
    ECHO "%_MAYAROOT%\bin\maya.exe"
    "%_MAYAROOT%\bin\render.exe" -s %startframe% -e %endframe% -b %byframe% -proj "%proj%" -rd %RD% "%mb%"
    goto end

:render_1819310
    ECHO.
    ECHO OF3D-CPU-DDG RENDER SCRIPT RUNNING @ %userId%
    ECHO.
    SET _V_MAYA=2015
    SET _MAYAROOT=C:\Program Files\Autodesk\Maya%_V_MAYA%
    SET _USER_CONFIG_ROOT=B:\custom_config\1819310
    SET _USER_SCRIPT_MEL=%_USER_CONFIG_ROOT%\scripts\mel
    SET _USER_PLUG_INS=%_USER_CONFIG_ROOT%\plugins
    SET _USER_PLUG_IN_OPIUMPIPE=%_USER_PLUG_INS%\opiumPipe
    SET _USER_PLUG_IN_OPIUMPIPE_BIN=%_USER_PLUG_IN_OPIUMPIPE%\bin
    SET _USER_PLUG_IN_OPIUMPIPE_MLL=%_USER_PLUG_IN_OPIUMPIPE%\mll
    SET _USER_PLUG_IN_PROXYPAINT=%_USER_PLUG_INS%\proxyPaint
    SET _USER_PLUG_IN_MTOA=%_USER_PLUG_INS%\mtoa_1.2.1.0
    SET _USER_PLUG_IN_YETI=%_USER_PLUG_INS%\pgYetiMaya_1.3.19
    
    SET _USER_SHADERS=%_USER_CONFIG_ROOT%\shaders
    SET _USER_SHADERS_ALSHADERS=%_USER_SHADERS%\alShaders-win-1.0.0rc7-ai4.2.2.0
    SET _USER_SHADERS_ALSHADERS_BIN=%_USER_SHADERS_ALSHADERS%\bin
    SET _USER_SHADERS_ALSHADERS_AE=%_USER_SHADERS_ALSHADERS%\ae
    
    SET _USER_MAYA_MODULE_PATH=%_USER_PLUG_IN_MTOA%;%_USER_PLUG_IN_YETI%
    SET _USER_MTOA_EXTENSIONS_PATH=%_USER_PLUG_IN_YETI%\plug-ins
    SET _USER_MTOA_PROCEDURAL_PATH=%_USER_PLUG_IN_YETI%\bin
    
    SET MAYA_PLUG_IN_PATH=%_USER_PLUG_IN_OPIUMPIPE_MLL%;%_USER_PLUG_IN_PROXYPAINT%;%_USER_PLUG_IN_MTOA%\plug-ins;%_USER_MTOA_EXTENSIONS_PATH%
    SET MAYA_SCRIPT_PATH=%_USER_SCRIPT_MEL%
    SET MTOA_TEMPLATES_PATH=%_USER_SHADERS_ALSHADERS_AE%
    SET MAYA_MODULE_PATH=%_USER_MAYA_MODULE_PATH%;%_USER_MAYA_PLUG_IN_PATH%
    SET MAYA_RENDER_DESC_PATH=%_USER_PLUG_IN_MTOA%
    SET MTOA_PROCEDURAL_PATH=%_USER_MTOA_PROCEDURAL_PATH%
    SET MTOA_EXTENSIONS_PATH=%_USER_MTOA_EXTENSIONS_PATH%
    SET PEREGRINEL_LICENSE=%_USER_PLUG_IN_YETI%\rlm\peregrinel.lic
    SET ARNOLD_PLUGIN_PATH=%_USER_SHADERS_ALSHADERS_BIN%
    SET PATH=%PATH%;%_USER_PLUG_IN_OPIUMPIPE_BIN%;%_USER_MTOA_PROCEDURAL_PATH%;%_USER_PLUG_IN_MTOA%\bin
    
    ECHO "%_MAYAROOT%\bin\maya.exe"
    "%_MAYAROOT%\bin\render.exe" -s %startframe% -e %endframe% -b %byframe% -proj "%proj%" -rd %RD% "%mb%"
    goto end

:end
ECHO "Batch Rendering Completed!"