//  Copyright (c)2012 Core CG
//  All rights reserved
//  www.core-cg.com


global proc AEcore_color_to_vectorTemplate( string $nodeName )
{	
	AEMentalCoreLogo("mc_core_color_to_vector_logo.png");
	
	editorTemplate -beginScrollLayout;
		editorTemplate -beginLayout "Parameters" -collapse 0;
			editorTemplate -addControl "input";
		editorTemplate -endLayout;

		AEmentalrayBaseTemplate($nodeName);

	editorTemplate -endScrollLayout;
}
