//  Copyright (c)2012 Core CG
//  All rights reserved
//  www.core-cg.com


global proc AEcore_vector_to_colorTemplate( string $nodeName )
{	
	AEMentalCoreLogo("mc_core_vector_to_color_logo.png");
	
	editorTemplate -beginScrollLayout;
		editorTemplate -beginLayout "Parameters" -collapse 0;
			editorTemplate -addControl "input";
		editorTemplate -endLayout;

		AEmentalrayBaseTemplate($nodeName);

	editorTemplate -endScrollLayout;
}
