//  Copyright (c)2012 Core CG
//  All rights reserved
//  www.core-cg.com


global proc AEcore_scalar_to_uvTemplate( string $nodeName )
{	
	AEMentalCoreLogo("mc_core_scalar_to_uv_logo.png");
	
	editorTemplate -beginScrollLayout;
		editorTemplate -beginLayout "Parameters" -collapse 0;
			editorTemplate -addControl "inputU";
			editorTemplate -addControl "inputV";
		editorTemplate -endLayout;

		AEmentalrayBaseTemplate($nodeName);

	editorTemplate -endScrollLayout;
}
